name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'TheDen-Bot'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: actions/labeler@v5
